In [1]:
import pandas as pd

anime_encoder_path = "../../data/anime_encoder.csv"
anime_csv_path = "../../data/anime.csv"

In [2]:
item_encoder_df = pd.read_csv(anime_encoder_path)
item_encoder_df.rename(columns={
            "Orignal Id":"original_id",
            "Encoded Id":"encoded_id"
            }, inplace=True)
item_encoder_df

      original_id  encoded_id
0               1           0
1               6           1
2               7           2
3               8           3
4              15           4
...           ...         ...
5564        45615        5564
5565        45616        5565
5566        46000        5566
5567        47398        5567
5568        48177        5568

[5569 rows x 2 columns]

In [3]:

df_anime = pd.read_csv(anime_csv_path)
df_anime = df_anime.join(item_encoder_df.set_index("original_id"), on="MAL_ID", how="inner")
df_anime

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1,encoded_id
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0,0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0,1
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0,2
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0,3
5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",Unknown,アイシールド21,TV,145,"Apr 6, 2005 to Mar 19, 2008",Spring 2005,...,14904.0,22811.0,16734.0,6206.0,2621.0,795.0,336.0,140.0,151.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17448,45615,Deep Sea Tentacle,Unknown,"Dementia, Music",Deep Sea Tentacle,Deep Sea Tentacle,ONA,1,"Jul 16, 2007",Unknown,...,Unknown,1.0,2.0,4.0,6.0,11.0,2.0,2.0,4.0,5564
17449,45616,Wakame Buildings,Unknown,"Dementia, Music",Seaweed Buildings,ワカメビルディング,ONA,1,"Jul 25, 2007",Unknown,...,Unknown,2.0,1.0,6.0,8.0,5.0,3.0,3.0,3.0,5565
17463,46000,2.43: Seiin Koukou Danshi Volley-bu Mini Anime,Unknown,Slice of Life,Unknown,2.43 清陰高校男子バレー部 ミニアニメ,ONA,8,"Nov 1, 2020 to Nov 27, 2020",Unknown,...,1.0,5.0,8.0,22.0,26.0,11.0,1.0,6.0,5.0,5566
17504,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,Unknown,キメツ学園 バレンタイン編,ONA,4,"Feb 14, 2021",Unknown,...,257.0,616.0,1422.0,1433.0,631.0,165.0,73.0,44.0,43.0,5567
17526,48177,Ichiban Chikakute Tooi Hoshi,Unknown,"Music, Drama",Unknown,一番近くて遠い星,ONA,1,"Feb 18, 2021",Unknown,...,Unknown,3.0,11.0,11.0,10.0,1.0,1.0,Unknown,Unknown,5568

In [4]:
df_anime[df_anime["English name"].apply(lambda x: True if "naruto" in x.lower() else False)]

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1,encoded_id
10,20,Naruto,7.91,"Action, Adventure, Comedy, Super Power, Martia...",Naruto,ナルト,TV,220,"Oct 3, 2002 to Feb 8, 2007",Fall 2002,...,234481.0,345563.0,286175.0,108155.0,46886.0,15477.0,6098.0,3582.0,5310.0,9
1574,1735,Naruto: Shippuuden,8.16,"Action, Adventure, Comedy, Super Power, Martia...",Naruto:Shippuden,ナルト- 疾風伝,TV,500,"Feb 15, 2007 to Mar 23, 2017",Winter 2007,...,213677.0,239113.0,175685.0,75970.0,36221.0,15913.0,6661.0,3383.0,4245.0,806
6875,12979,Naruto SD: Rock Lee no Seishun Full-Power Ninden,7.14,"Action, Comedy, Parody",NARUTO Spin-Off:Rock Lee & His Ninja Pals,ナルトSD ロック・リーの青春フルパワー忍伝,TV,51,"Apr 3, 2012 to Mar 26, 2013",Spring 2012,...,3349.0,6394.0,8482.0,5290.0,3050.0,1308.0,646.0,461.0,475.0,2448

In [5]:
df_anime[df_anime["English name"].apply(lambda x: True if "one piece" in x.lower() else False)]

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1,encoded_id
11,21,One Piece,8.52,"Action, Adventure, Comedy, Super Power, Drama,...",One Piece,ONE PIECE,TV,Unknown,"Oct 20, 1999 to ?",Fall 1999,...,166186.0,141755.0,85424.0,35342.0,19019.0,8201.0,3675.0,2616.0,6340.0,10
16015,40181,Look Plus One Piece Special Movie,5.83,"Adventure, Parody, Shounen",Look Plus One Piece Special Movie,ルックプラス ワンピース スペシャルムービー,ONA,1,"Jul 29, 2019",Unknown,...,27.0,47.0,81.0,152.0,188.0,59.0,29.0,21.0,27.0,5232

In [6]:
df_anime[df_anime["English name"].apply(lambda x: True if "one punch" in x.lower() else False)]

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1,encoded_id
10451,30276,One Punch Man,8.57,"Action, Sci-Fi, Comedy, Parody, Super Power, S...",One Punch Man,ワンパンマン,TV,12,"Oct 5, 2015 to Dec 21, 2015",Fall 2015,...,465041.0,403832.0,172181.0,47365.0,17873.0,5706.0,2279.0,1448.0,2733.0,3349

In [7]:
df_anime[df_anime["English name"].apply(lambda x: True if "gintama" in x.lower() else False)]

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1,encoded_id
833,918,Gintama,8.96,"Action, Comedy, Historical, Parody, Samurai, S...",Gintama,銀魂,TV,201,"Apr 4, 2006 to Mar 25, 2010",Spring 2006,...,74869.0,52666.0,27675.0,11208.0,6423.0,2934.0,1299.0,850.0,2743.0,496
6006,9969,Gintama',9.08,"Action, Sci-Fi, Comedy, Historical, Parody, Sa...",Gintama Season 2,銀魂',TV,51,"Apr 4, 2011 to Mar 26, 2012",Spring 2011,...,44740.0,24294.0,9584.0,3222.0,1655.0,694.0,338.0,437.0,2910.0,2177
7261,15417,Gintama': Enchousen,9.04,"Action, Comedy, Historical, Parody, Samurai, S...",Gintama:Enchousen,銀魂' 延長戦,TV,13,"Oct 4, 2012 to Mar 28, 2013",Fall 2012,...,32100.0,17753.0,6900.0,1968.0,867.0,303.0,184.0,145.0,2059.0,2565
9913,28977,Gintama°,9.1,"Action, Comedy, Historical, Parody, Samurai, S...",Gintama Season 4,銀魂°,TV,51,"Apr 8, 2015 to Mar 30, 2016",Spring 2015,...,37902.0,21360.0,10215.0,3898.0,2311.0,952.0,648.0,1100.0,4508.0,3260
12242,34096,Gintama.,8.99,"Action, Comedy, Historical, Parody, Samurai, S...",Gintama Season 5,銀魂。,TV,12,"Jan 9, 2017 to Mar 27, 2017",Winter 2017,...,26546.0,15035.0,5856.0,1926.0,827.0,338.0,172.0,126.0,1628.0,3976
13289,35843,Gintama.: Porori-hen,8.53,"Action, Comedy, Historical, Parody, Samurai, S...",Gintama.:Slip Arc,銀魂。ポロリ編,TV,13,"Oct 2, 2017 to Dec 25, 2017",Fall 2017,...,15760.0,16162.0,7886.0,2413.0,813.0,338.0,146.0,94.0,726.0,4297
13901,36838,Gintama.: Shirogane no Tamashii-hen,8.81,"Action, Comedy, Historical, Parody, Samurai, S...",Gintama.:Silver Soul Arc,銀魂. 銀ノ魂篇,TV,12,"Jan 8, 2018 to Mar 26, 2018",Winter 2018,...,16948.0,12097.0,5008.0,1484.0,606.0,292.0,148.0,88.0,951.0,4502
14293,37491,Gintama.: Shirogane no Tamashii-hen - Kouhan-sen,8.86,"Action, Sci-Fi, Comedy, Historical, Parody, Sa...",Gintama.:Silver Soul Arc - Second Half War,銀魂. 銀ノ魂篇 後半戦,TV,14,"Jul 9, 2018 to Oct 8, 2018",Summer 2018,...,15335.0,10230.0,3947.0,1229.0,500.0,210.0,97.0,59.0,874.0,4653

In [26]:
df_anime[df_anime["English name"].apply(lambda x: True if "golden wind" in x.lower() else False)]

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1,encoded_id
14623,37991,JoJo no Kimyou na Bouken Part 5: Ougon no Kaze,8.61,"Action, Adventure, Shounen",JoJo's Bizarre Adventure:Golden Wind,ジョジョの奇妙な冒険 黄金の風,TV,39,"Oct 6, 2018 to Jul 28, 2019",Fall 2018,...,112273.0,85285.0,33502.0,10377.0,4176.0,2031.0,854.0,523.0,1591.0,4790